// <auto-generated />
using System;
using BackSistemaUbala;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackSistemaUbala.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20220507043952_Roles_Usuarios")]
    partial class Roles_Usuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackSistemaUbala.Models.AlumnoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<string>("NombreAcudiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroAcudiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoSangre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.GrupoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Curso")
                        .HasColumnType("int");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.MateriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.MateriaProfesorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdProfesor");

                    b.HasIndex("IdUser");

                    b.ToTable("MateriaProfesores");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.NotaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DefinitivaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdAlumno")
                        .HasColumnType("int");

                    b.Property<int>("IdMateriaProfesor")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NotaHacer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaSaber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NotaSer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdMateriaProfesor");

                    b.HasIndex("IdUser");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.ProfesorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.RolModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcíon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.UsuarioModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreAcudiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroAcudiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoSangre")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("General_back.Security.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationUserRole");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.AlumnoModel", b =>
                {
                    b.HasOne("BackSistemaUbala.Models.GrupoModel", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.MateriaProfesorModel", b =>
                {
                    b.HasOne("BackSistemaUbala.Models.MateriaModel", "Materia")
                        .WithMany("MateriaProfesores")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackSistemaUbala.Models.ProfesorModel", "Profesor")
                        .WithMany("MateriasProfesor")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackSistemaUbala.Models.UsuarioModel", "Usuario")
                        .WithMany("MateriasProfesor")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Materia");

                    b.Navigation("Profesor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.NotaModel", b =>
                {
                    b.HasOne("BackSistemaUbala.Models.AlumnoModel", "Alumno")
                        .WithMany("NotasAlumnos")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackSistemaUbala.Models.MateriaProfesorModel", "MateriaProfesor")
                        .WithMany("Notas")
                        .HasForeignKey("IdMateriaProfesor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackSistemaUbala.Models.UsuarioModel", "Usuario")
                        .WithMany("NotasAlumnos")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Alumno");

                    b.Navigation("MateriaProfesor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.ProfesorModel", b =>
                {
                    b.HasOne("BackSistemaUbala.Models.GrupoModel", "Grupo")
                        .WithMany("Profesores")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.UsuarioModel", b =>
                {
                    b.HasOne("BackSistemaUbala.Models.GrupoModel", "Grupo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("General_back.Security.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("BackSistemaUbala.Models.RolModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackSistemaUbala.Models.UsuarioModel", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.AlumnoModel", b =>
                {
                    b.Navigation("NotasAlumnos");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.GrupoModel", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Profesores");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.MateriaModel", b =>
                {
                    b.Navigation("MateriaProfesores");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.MateriaProfesorModel", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.ProfesorModel", b =>
                {
                    b.Navigation("MateriasProfesor");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.RolModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackSistemaUbala.Models.UsuarioModel", b =>
                {
                    b.Navigation("MateriasProfesor");

                    b.Navigation("NotasAlumnos");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
